# Generated by Django 2.2.7 on 2019-11-29 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubeapi', '0002_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'video')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'video')},
        ),
    ]
