# Generated by Django 2.2.7 on 2019-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0003_auto_20191129_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(),
        ),
    ]
